<template>
    <b-row no-gutters>
        <b-col cols="3" class="scroll-spy-col">
            <b-list-group v-scroll-spy-active v-scroll-spy-link tag="ul" class="article-scroll-menu">
                <b-list-group-item v-for="(title, index) in titles" :key="index" tag="li" class="article-scroll-menu-item">
                    <a>{{ title }}</a>
                </b-list-group-item>
            </b-list-group>
        </b-col>
        <b-col cols="9">
            <div v-scroll-spy="{data: 'section', offset: 80}" class="article-scroll-content">
             <div>
                <h1>Disordered Eating</h1>
                <p>Struggles with eating issues are are about more than just food, though if you are suffering from these issues you may not be able to explain what else is happening. What you do know is that you struggle a lot more than you want to with eating or not eating, gaining weight, keeping your current weight, or losing weight. All this holds so much of your attention that it's hard to get to what these eating issues are really about. So what is this "disordered eating" all about, then?</p>
            </div>
            <div>
                <h2>Disordered Eating - Terms And Diagnosis</h2>
                <p>A lot of terms are used among people who address eating related concerns. Those who are less familiar with the issues related to disordered eating may not immediately understand many of these terms.  This brief introduction to those terms will help you navigate information that you collect on eating disorders through those various resources you may have identified.</p>
            </div>
            <div>
                <h4>Binge Eating</h4>
                <p>A binge is defined as eating an amount of food that is definitely larger than most individuals would eat under similar circumstances.  Although a binge is defined as occurring within a specific period of time, it can occur in different places but still be part of the same binge episode.   For example, an individual may begin a binge in a grocery store or restaurant, and then still be on the binge upon returning home.  Another defining feature of a binge is that the eating is experienced as out of the person's control. While this usually means that an impulsive act takes place with no planning, there are times when the binge is planned because the urge originates and accumulates over a period of time when there is no access to food.  Once the eating begins, however, and during the anticipation of the episode, the inevitable and uncontrollable sensation still occurs.   If, for some reason the planned binge cannot occur (somebody stops by, for example), the urge becomes complicated by a lot of nervousness.   Immediately following the binge, there is a period of relief or even of feeling intensely satisfied.  However, this is typically followed by strong shame and feeling disgusted with one's self.   Because of this shame reaction, there is a wish and full intention to never behave in this manner again.  However, much of the binging is a reaction to a troubled self-image, so this reaction may actually play a role in the next binge occurring.  For many individuals, especially those who have been struggling for a long time with binging, depression eventually develops as the person realizes she/he has become trapped within a cruel binge-cycle.</p>
            </div>
            <div>
                <h4>Purging</h4>
                <p>A purge is defined as self-induced actions on the body with the intentional goal of avoiding the weight gain that is feared from having just eaten.   The most common form of purging is self-induced vomiting. The purge is usually experienced as an uncontrollable urge that comes from the fear of weight gain.   However, individuals who have been struggling with disordered eating for longer periods may have grown so accustomed to having the urge that they don't feel the urgency; rather the act of purging becomes a necessary or  matter-of-fact task that is decided upon almost automatically.   Phrases such as "taking care of it" or "dealing with it" or "getting rid of it" are often used to describe purging.</p>
                <p>Because disordered eating has become more widespread and most people immediately associate purging with disordered eating, there is often a great deal of shame associated with purging.   Persons struggling often report intense shame the first time they ever made themselves vomit and yet they still find themselves unable to refrain from doing it again when the emotional turmoil returns.</p>
            </div>
            <div>
                <h4>Diagnosis</h4>
                <p>A diagnosis is a name or term used by professionals in order to communicate with each other and organize the different problems experienced by all those they serve.  When certain patterns of problems begin to emerge in individuals, mental health professionals can recognize them when they occur in enough different people that it appears to be the same problem.  Sometimes, it feels helpful for the person with the problem to have a name for what they struggle with, as well.  However, having a diagnosis of an Eating Disorder does not mean you cannot overcome it.  It may make sense to view it as an illness because it helps to emphasize how important it is to get help to overcome it.  However, simply knowing what the name of a person's problem is does not solve it.  Therefore, it might be more helpful to focus less on the diagnosis or on whether a person "really has" an eating disorder.  In fact, it may be even more helpful to think less in terms of "an eating disorder" and more in terms of "disordered eating."   The reason for this shift is that people often become passive when they think of "having a disorder" and they come to view themselves as "defective"; if they think in terms of "disordered eating" they are dealing with a behavior, a set of actions and reactions to life's challenges.  From there it is easier to shift toward learning a new set of actions and reactions without the identity of a defective person.</p>
                <p>Nevertheless, it is unavoidable that most people struggling with disordered eating (either themselves or through someone they love who is struggling) will eventually come across diagnostic terms.  Therefore, we'd like to include some information so you know what these somewhat familiar terms actually refer to.</p>
            </div>
            <div>
                <h4>Anorexia (or Anorexia Nervosa)</h4>
                <p>The term Anorexia Nervosa is a diagnosis applied to an individual who meets very specific criteria. The defining feature of anorexia is that the individual refuses to maintain a minimally normal body weight. (Specifically, to be assigned a diagnosis of anorexia, an individual must be at 85% of their normal body weight or lower).  The person with anorexia or similar difficulties is extremely focused on a pursuit of thinness.   She (or he) is intensely afraid of gaining weight.  Much of the fear is linked to another defining feature of anorexia: a distorted view of how one's body actually is, perceiving fat where there is clear emaciation or viewing the less "thin" parts of their body as indicative that they are entirely fat. This perception keeps the need to lose weight or prevent weight gain in control of the individual’s priorities.  A final feature that defines anorexia as a diagnosis is (for women who have already begun having their menstrual period) an absence of at least 3 consecutive menses.</p>
                <p>There are many misconceptions around Anorexia, among the more common is that if a person does not employ self-induced vomiting, then they're "not anorexic."   In fact, these misconceptions are based on confusion between bulimia nervosa and anorexia nervosa.  Anorexia can be diagnosed if the individual uses purging methods to prevent weight gain (and these individuals often struggle with binge episodes which make the purging behaviors feel absolutely mandatory).  This is regarded as the Binge Eating/Purging Type of Anorexia.  Anorexia Nervosa can also be diagnosed even if the person never engages in purge behaviors, relying on a strict low calorie diet.  This is regarded as Anorexia Nervosa, Restricting Type.</p>
                <p>Another unfortunate misconception is that those suffering from Anorexia simply have a desirable level of self-discipline to not eat.  Sometimes, individuals with severe body image concerns will profess a wish that they could be anorexic.  The mechanism that maintains the behaviors associated with anorexia is not discipline.  It’s fear.  What those with such misconception-based envy don't realize is that they are also wishing for the extreme fear and painful confusion that comes from struggling with a completely kidnapped way of life that those with anorexia experience.</p>
            </div>
            <div>
                <h4>Bulimia Nervosa</h4>
                <p>There are two fundamental indicators needed for a formal diagnosis of Bulimia Nervosa:</p>
                <ol>
                    <li>Binge eating (defined as eating amounts of food that are clearly larger than what most folks would eat) with a "beyond control" quality to the eating episodes, and</li>
                    <li>A Behavior that aims to compensate for the expected weight gain that, naturally, would result from eating more than is usual.</li>
                </ol>
                <p>A problem in making the diagnosis of bulimia nervosa is that many people eat “more than usual” from time to time, yet they do not meet the criteria for a diagnosis of bulimia nervosa. For example, many people "binge" eat at holiday dinners. Even closer to "bulimic" behavior, many of us find ourselves eating more when we are feeling very down. Yet, we don't meet the criteria for a bulimia diagnosis. The difference between those of us with such common excessive-eating episodes and someone who has bulimia nervosa is that the latter binge-eat frequently (more than twice a week) and have lost control over their eating behaviors. For them, what we experience on occasion is more of an ongoing struggle.  Their lives typically begin to revolve around concerns about food. Often, they divide their days into ‘good' days when they have no desire to binge and ‘bad' days when the compulsion to binge becomes irresistible.  Before a person will be diagnosed with bulimia, she/he will have had at least an average of two binge-eating episodes a week for at least three months, and she/he will have experienced these eating episodes as uncontrollable (unable to stop even though she/he knows it's excessive eating). Additionally, a person struggling with bulimia regularly engages in either strict dieting (or simply not eating), excessive exercising between these binges episodes, self-induced vomiting, and/or use of  laxatives and diuretics to lose weight. All of these behaviors operate under a persistent concern with body shape and weight. Because of the awareness that these binge episodes are not normal, there is typically a great deal of shame that leads to keeping the difficulty a secret.</p>
            </div>
            <div>
                <h4>Disordered Eating Which Does Not Meet Diagnostic Criteria</h4>
                <p>Perhaps the single most important thing to keep in mind about the diagnoses of disordered eating is that anyone who is struggling to a degree that does not meet the criteria for a specific eating disorder is in a struggle that is as legitimate as any diagnosis could ever be.  Diagnostic criteria are constantly changing as mental health professionals learn more and more about the struggles we all face, and they are still learning about disordered eating.  Therefore, diagnostic criteria and terminology may also change. For example, there is a condition referred to as Binge Eating Disorder still undergoing research before being included as a formal diagnosis.  Binge Eating Disorder involves uncontrollable eating episodes but does not consistently involve a behavior to compensate.  This struggle impacts a great many people, a significant number of whom struggle with obesity.  These individuals often seek help  toward weight loss and the underlying issues leading to the frequent binges are not attended to because they’re not thought of has having disordered eating.</p>
                <p>Many individuals suffer from some level or type of eating behavior that is disrupting their lives.  They are struggling with a confusing problem that feels both absurd and easy to fix but carries an intensity and a depth that makes it hard to place aside.  For some, disordered eating is about a different kind of hunger… and for others, it’s about a painful sense of being too full of some of life’s vulnerabilities.  For others, it’s both.  Either way, the difficulty is real and the availability of help is there.</p>
                <br>
            </div>
            <div>
                <h2>Understanding Disordered Eating</h2>
            </div>
            <div>
                <h4>A Different Kind of Hunger</h4>
                <p>If you are struggling with eating issues, you probably already know that it’s not just about food you may not be able to explain what else it's about, but you know that food is not the main thing happening with you. What you do know is that you struggle a lot more than you want to with eating or not eating, gaining weight, keeping your current weight, or losing weight.  All this holds so much of your attention that it's hard to get to what these "eating issues" are really about. So what is this "disordered eating" all about, then?</p>
            </div>
            <div>
                <h4>Emotional Upheaval and Powerful Feelings</h4>
                <p>Eating issues are about emotional upheaval and powerful feelings. This is important to keep in mind because it is something you have in common with everyone else, whether they are struggling with eating issues or not. When it comes to working through the difficulties you're having with food, this will have a big impact because your feelings and the connections they provide to others will feed you more than the disordered eating ever can. Why? Because others have emotional upheaval and powerful feelings, too, and they're hungry for connection, too.</p>
                <p>So, how is it that you struggle with eating issues if they don't? Although there may be different backgrounds and experiences, one common factor is that those who struggle with disordered eating have powerful emotions in an upheaval because those feelings have gone unexpressed. In short, you keep much of your feelings inside, perhaps so far inside that even you have lost touch with them.  More than likely, you were keeping them inside before the eating difficulties began, and you may have done this for various reasons. Perhaps, there was a time that you did show your feelings, but they went ignored. those who you needed to listen were busy or not as tuned in to you at the time. Perhaps, your feelings weren't ignored but they were treated as unimportant. you were told not to worry about it, to get over it, or that everyone feels that way. Maybe these messages were intended to help and make you feel better, but you were left carrying these feelings. alone and out on a limb.  Unfortunately, for some of you, these feelings were made fun of. or you saw others that were mocked and you became afraid the same would happen to you if you showed your feelings. You didn't want to be viewed as "weak" or "silly" or "crybaby" or "complaining all the time", so you just kept them inside. where they still are.</p>
                <p>Whatever you do in your struggle with food, whether it is binge uncontrollably, make yourself throw up, exercise compulsively, or deprive yourself of food when you are wanting to enjoy something to eat look inside, and there they are, those feelings waiting like children for someone (hopefully you) to pick them up and hold them.</p>
            </div>
            <div>
                <h4>Feeling Hurt and Scared when Trying to Relate to Others</h4>
                <p>Disordered eating is also about feeling hurt and scared when trying to connect with others or develop relationships with them.  It's about being hungry for approval, for this sense that others think you're good enough to be with, that they consider you as compatible with them.  More than that, though, you want to be accepted.</p>
                <p>Disordered eating often goes even deeper than that.  It's a different kind of hunger than what you usually think of.  It's a hunger for understanding, for this sense that other people see things the way you do, that they "get it" when it comes to the way life feels sometimes, the way you want it to be, but it's hard to take a chance when everyone else seems to be on the same page one that seems terribly different than yours.</p>
                <p>And disordered eating is about being hungry for company.  You're a human being. by definition you are a social being and being connected with others who are actively in your life is a natural and healthy need. Sometimes, though, it's easy to get bogged down by doubts that others want to have you around so you withdraw or you may even start to push them away. None of this changes the fact that you're often lonely and just wish you had a group of people to call your friends, to hang out with, and to turn to when all of life's hunger pains start to hurt more. Sometimes the hunger for company is even more subtle. You may actually have a lot of people in your life and enjoy a good social circle, but you know, deep inside, that they don't really know you, so you end up feeling alone or vulnerable. and just with all these emotional hungers, you do one of two things or both of them: feed the hunger by eating more food than your body needs or starve the person who's hungry so she doesn't bother you anymore.</p>
            </div>
            <div>
                <h4>Feeling Like a Failure When it Seems You Have to be Perfect</h4>
                <p>Even though you may know, in your head, that nobody is perfect, struggling with disordered eating usually means struggling with the things about you that are not perfect. It's hard not to struggle with those things. We live in a culture that says you can be perfect if you just do the right things: usually this is related to buying products, but the end result is a media-influenced perception that makes it appear that others are much closer to some idea of "perfect" than you are. This, of course, leads you to want to get closer to a distorted idea of who you are supposed to be: attractive enough, self-disciplined enough, smart enough, social enough, and whatever enough's you come up with on your own. Often, this involves seeking to be perfectly thin because much of the ideas of thinness in our culture are equated with being desirable. It becomes easy to believe that if you are thin enough, you'd be closer to being perfectly pretty.  Other things also get into the picture. It becomes important to have perfect grades or evaluations and you build your life around these things because, at the end of all the logic and perceptions, they seem to be the path to having others like you and, hopefully, love you. These things seem to be the way to get others to accept you with no reason to reject you.</p>
            </div>
            <div>
                <h4>It Is All About Control</h4>
                <p>All of these pursuits are related to a need for control. We all live in a world where anything can happen, a world where the opinion of others sometimes has an impact on you, and so you find yourself vulnerable in a world where, no matter how hard you try, it may not seem like enough. but you try and keep trying.  If you could be perfectly thin, and perfectly pretty, and perfectly disciplined, with perfect grades and a perfect attitude, then it seems there will be no room for doubt about your effort and ability and worth.  There would be no doubt about your being okay, and you could rest. But that time hasn't come yet. Perhaps it never will because, as human beings, we will always have shortcomings that make us feel less than that version of ourselves that feels like it would be good enough.</p>
                <p>When you feel these "good enough" versions of you slipping away, you feel powerless about whether life is going to turn out okay, and you need something to feel back in control of that.  Eating or resisting the natural need to eat gives you that sense of control for a little while, anyway. And since you know how to use food or starving to give you that sense of control, you hold onto it like the only friend you have in this whole wide scary world.</p>
                <p><i>&emsp;"If I can control what I eat!"<br>
                    &emsp;"Then I can control my weight."<br>
                    &emsp;"Then I can control how good I can feel about myself."<br>
                    &emsp;"Then everything will be okay."</i></p>
            </div>
            <div>
                <h4>So It Also IS About Food?</h4>
                <p>If all of these issues from being loved and accepted and needing greater control are what disordered eating is about, then why eating?  Why does it seem to be about food? Although there are no complete explanations, it does seem like a somewhat logical choice as a coping device when a few commonly accepted ideas are considered.</p>
                <p>1.  Food keeps us alive - physically. First of all, we need food to stay alive. At a basic physiological level, food is a good coping device for survival. Thinking from a more holistic perspective, it seems our body knows food is about survival and this awareness shows up psychologically. So, when we feel vulnerable it makes sense that we try to deal with it using food.</p>
                <p>2.  Food is a symbol of nurturing. In many cultures throughout the world, including the United States, food is a symbol of caring and loving.  Simply examine our holiday rituals and you'll find Thanksgiving Dinner, Valentine Chocolates, Halloween Candy, and other celebrations that revolve around sharing meals.  Further, we tend to cook dinner or prepare breakfast as part of romantic experiences and we take ourselves out for a food treat when we've had a bad day.</p>
                <p>3.  Eating, food, and weight are weaved into our emotional experiences.
                The cultural impact of food, eating, and weight are clear on more subtle levels as well. They are linked to emotions in many ways in which we express ourselves. In terms of language alone, we use phrases that reflect this link.</p>
                <p><i>&emsp;She's/He's just starving for affection.<br>
                    &emsp;He's/She's hungry for love.<br>
                    &emsp;He's/She's just feeding his/her lies.<br>
                    &emsp;She/He just eats up all that flattery.<br>
                    &emsp;That's a hard fact to swallow.</i></p>
                <p>Often so much attention is paid to disordered eating that we neglect the very normal and common link between eating and emotional experiences.  Consider going to the movies. Typically, if there is popcorn in your lap, you're eating it much faster during the scary scenes, the scenes where the romance is finally about to come alive, and the scenes where the sad ending is clearly on its way.</p>
                <p>So, keep in mind that, even though you may realize your eating and your concerns about weight have evolved into problems, you are struggling with an extreme experience and you aren't as "abnormal" as you may fear. You, as a person, are okay. It's the perceptions and assumptions you've developed and the feelings and behaviors that come from these perception that need adjusting. It may be very difficult to start adjusting your way of understanding yourself and your life. But you can do it. One of the things you can do to begin making these adjustments is to ask yourself a question regarding the role eating plays in your life.</p>
            </div>
            <div>
                <h4>What Are You Really Hungry For?</h4>
                <p>We're all human, and although your unique life situations leave you with different needs and different intensities of those needs, one thing we all have in common to some extent is that we are interpersonal beings. In other words, many of our needs involve how others regard us or how we believe they do. Therefore, it is important to not simply ask what role eating plays in your life but also how is it linked to some of our interpersonal needs, fears, and hurts.</p>
                <p>So, if you are struggling with disordered eating, chances are high that--in your unique personal way--you are hungry for love, approval and acceptance.  It is difficult, even painful, when you can't know for certain that you will be fed these nurturing experiences. You then become very hungry for control. You want to be loved in a way that shows you’re truly special, a way that doesn't leave you worried that others have some qualities that are so bright you won't be noticed and valued, too.   You're hungry for approval, being told in many different ways that you’re already good enough!  You crave acceptance, because sometimes it is hard to feel like you really belong and that you actually and completely deserve to be a part of it all!</p>
                <p>Sometimes, you simply feel like you don't have these things or that you may lose them if you do. Other times you know you have these things and you feel foolish for worrying, but you only know them in logical terms. You can see that others care for you so you don't know why you should struggle so much. You may know that you have love, approval, and acceptance, but you don't believe it.  Knowing and Believing are two different things. One is logical and based on fact. The other is more intuitive and based on faith and trust.  When you know you are loved, you may not believe it emotionally. The emotional doubts then leave you wanting a greater sense of Control.</p>
                <p>So much of life seems out of your control or authority. Whether it's parents or peers, coaches or teachers, or the larger social culture, it often seems that others determine whether you receive the acceptance and approval you need to feel good about being who you are! Life seems like a series of questions that are so complicated, whose answers are so unpredictable, that life becomes scary and it hurts!!!</p>
                <p><i>&emsp;What clothes do I have to wear?<br>
                    &emsp;Will I fall in love with someone?<br>
                    &emsp;Where do I go after I'm done with school?<br>
                    &emsp;What if I fail?<br>
                    &emsp;How do I get people to like me?<br>
                    &emsp;Will someone fall in love with me?<br>
                    &emsp;What if I don't get good grades?<br>
                    &emsp;Who do my parents expect me to be?</i></p>
            </div>
            <div>
                <h4>Trying to Make Life More Simple</h4>
                <p>And for each of these questions, you can add another hundred every day, leaving you feeling overwhelmed to the point where you just need to make life simple!  The need to keep things simple then impacts your way of thinking about things. One of the ways you may try to make life seem a little more manageable is thinking in extremes. You keep your world black and white because all the different shades of gray are too hard to define and you're struggling enough with how to define yourself as it is. As this way of thinking takes over, then most of your life  becomes a matter of all or nothing. You only leave yourself two choices.  So there is only fat or thin--with nothing in between, beautiful or ugly--with nothing in between, and then perfect or worthless--with nothing in between.</p>
                <p>Eating, then, becomes the one thing that can be controlled in all of these aspects!  But there is help available.  Contact CAPS if you'd like to talk to someone who may know how to help you live your life more completely and with more comforting self-acceptance than the eating issues that have become  the problem instead of a solution.</p>
                <br>
            </div>
            <div>
                <h2>Disordered Eating: How To Help?</h2>
            </div>
            <div>
                <h4>Let Them Know They're Not Alone</h4>
                <p>Often, individuals struggling with disordered eating carry a strong sense of shame about their struggle. They, strive to keep their difficulty a secret. Also, there is a strong belief, often accurately so, that others will not understand the struggle they have with eating and food.  Therefore, individuals who struggle with disordered eating often feel terribly alone.  Even if they have friends, the eating issues consume so much of their life that there's a big part of them that few, if any people, even know exists. and this is very, very lonely.  So, the first thing to do as an ally to someone struggling with disordered eating is to assure the friend or loved one that they are not alone.  The best way to convey this is to listen.  Let them know that, if they want or need to just talk out some of their fears, hurt, or even anger, that you will be there so they can have someone to say these things out loud to.   It may not seem like much, but there is a big difference between having all sorts of painful and confusing feelings swimming around inside and having them uttered out loud where someone else hears them.  It is not the response that helps so much as the fact that someone hears.  When someone hears, one of the most painful aspects of struggling with disordered eating is diminished: feeling alone.</p>
            </div>
            <div>
                <h4>Encourage Them to Seek Help</h4>
                <p>In helping someone struggling with disordered eating issues, it's often important to first know the ways in which you cannot help.  If you find yourself as the only person that is consistently there to help, you are likely assuming more roles than you have sufficient strength and understanding to really give the person struggling what she (or he) needs.  In sharing your support, it's important to also share your limitations. Emphasize that your support is one important aspect of their healing, but that others are also needed. Because a defining feature of any struggle with disordered eating issues is a reduction of the person into one dimension, it is important the healing occur at the various levels of the person’s life which have been neglected as a result of the disordered eating. Each friend or loved one in a person's life probably meets different needs and highlights different qualities in that person's life.  So, gradually, helping the person struggling to realize that trusting others (at a pace that feels safe) is as important as your support. Usually personal and professional help is needed. A mental health professional, a physician, and a nutritionist are typically involved in a professional team approach, each with expertise to address the forgotten or neglected dimensions of the intricate human being who is struggling.</p>
            </div>
            <div>
                <h4>Be Yourself</h4>
                <p>They are just two simple but very important words: Be Yourself.  The first word is critical because often loved ones of someone struggling with disordered eating become frustrated  because they want to DO something to make things better.  However, it's who you are that matters more than what you can actually do.  If you are a friend, a parent, a roommate, a romantic partner, or a teacher, be who you are with them instead of trying to do things for them.  Often, individuals who are struggling with disordered eating become frustrated because loved ones trying to help end up approaching them more like therapists or physicians or nutritionists rather than the close personal connection that they are. It's important to resist the inclination to analyze, interpret, or direct the behaviors of the person who is struggling.  Often those trying to help feel the urge to say things like, "I think you do this because of the way." or "There are serious medical repercussions that you are bringing on to yourself when you." or "You need to eat more of." However well intentioned, such statements are seldom helpful because none of these are within the role that you are most needed for: a loved one who loves and listens., Remember, it's most important to be a source of support and not a source of suggestions.</p>
                <p>It is okay to acknowledge the full range of your feelings, not just the "positive" ones like loving and caring and patient.   Sometimes you will feel anger, fear or frustration and it is okay to acknowledge these.  It seems scary to think of telling someone who seems so fragile that you are angry or frustrated because you don't want to hurt him (or her).  Of course, there are times that a person is too fragile to hear these things and you need to use the best judgment you have.  Generally speaking, however, you play an important role when you can be genuinely loving and frustrated, genuinely caring and angry.  The reason that this is so important is that most people who struggle with disordered eating have entered a world where most things are EITHER/OR.  They have forgotten that people can be loving and frustrated at the same time.  So, when they see their loved ones able to be complex, to carry some seemingly contradictory feelings, it helps them see that they too can be complex individuals rather than the single dimension-being that disordered eating creates.</p>
                <p>So, in the end, being helpful to someone struggling with disordered eating is, ultimately,  just being a genuine person in such a way that shows them it's okay for them to be who they genuinely are right now: someone struggling; someone needing to know it's okay to need support and get it from those who care.</p>
                <br>
            </div>
            <div>
                <h2>Disordered Eating: What To Say?</h2>
            </div>
            <div>
                <h4>What To Say To Someone You're Concerned About</h4>
                <p>It can feel quite intimidating to approach someone who you believe is struggling with disordered eating.  You likely have observed several warning signs that make it seem obvious to you that there is a problem.  However, it's difficult to come up with a way to voice your concern without fearing that you are going to be met with a strong reaction of denial or anger or both.   Because both reactions are quite possible, it is important to approach this person in such a way that minimizes defensiveness and delivers the message that you are available as a supportive person.</p>
            </div>
            <div>
                <h4>When and Where To Approach?</h4>
                <p>If there have been enough indications that warrant taking the chance to approach someone about disordered eating, the first thing to consider is when and where to talk to the person you are worried about.  It is important to choose a calm time to have the discussion.  Do not begin if there have any recent arguments or other incidents that have been emotional.  As a rule, this almost certainly means that approaching a person struggling with eating issues should not occur during or near a meal time. Choose a neutral time such as the middle of the day or the middle evening hours.  Meal times and transition times are stressful for a person struggling with disordered eating and respecting that she or he experiences a lot of vulnerability around this issue is important.  Confronting her/him during a stressful time is likely to be unsuccessful.</p>
                <p>Also, it's important to select a place that feels safe for the person who is struggling.  Have only the closest person or persons present, but no more than 2 or 3.  Too many people may be overwhelming, and this might make the experience seem like attacking more than caring.  Again, avoid places that are associated with weight or food such as kitchens, dining rooms, and fitness areas.  With the fundamental environment as safe as possible, you have a greater chance of being heard and, in return, hearing what the person you're trying to support is actually feeling.</p>
            </div>
            <div>
                <h4>Finding the Right Words</h4>
                <p>Of course, the most intimidating and difficult aspect of approaching someone struggling with disordered eating is actually finding the right words.  In fact, coming up with what to say first is often extremely difficult.  As simple as it sounds, what may be both the easiest and most effective is to simply state that you have something you want to talk about.  You are likely to be feeling anxious, perhaps even downright afraid of doing more harm than good.  It's okay and natural that you have these feelings. In fact, your feelings can play a role in helping you approach the person you're worried about:  Share those feelings!   If you examine the feelings you have, you will probably find that you have conflicting feelings that place you in a bit of a predicament:</p>
                <p><i><b>&emsp;You want to respect their privacy, BUT you are worried or scared for their well being.<br>
                         &emsp;You want to help, BUT you are afraid you're going to cause even more hurt or problems.</b></i></p>
                <p>The first thing to keep in mind is that all of these feelings are valid and true.  Change the word but to the word and, then share all of these feelings with the person to whom you are offering your support.  Consider the following suggestion:</p>
            </div>
            <div>
                <h4>Can We Talk?</h4>
                <p><i>"I want to talk to you about something, and it’s hard for me because I know it’s very personal. I’m torn between wanting to help and wanting to keep quiet so I don't upset you or push you away."</i></p>
                <p>Approaching this way can have a positive effect in several important ways.  First of all, it involves you sharing your feelings, and this helps to keep the emotions from running the show. (That can risk breaking down crying or getting unexpectedly angry).   Once acknowledged, emotions are more likely to simply just "be there" rather than "taking over" making your words come out wrong or getting in the way of your first priority: communicating that you want to help. Another advantage of beginning by sharing your feelings is that she/he is likely feeling quite a storm of emotions also.   But she/he may not have named them as such.  By you saying what you are feeling, the person struggling will be more likely to say, “I feel that way, too” or at least say “I’m feeling a lot, too”.  This leads to the most important advantage of expressing your emotions:  it centers emotions as the topic of the conversation rather than an impersonal and distressing eating disorder.Now that you have introduced the issue and set the stage by sharing the emotions that are being felt by everyone involved, what next?  Well, she or he may suspect that you are going to bring up the disordered eating because she or he has most likely been aware of it and struggling with this.   Of course, this may be the most vulnerable part because your very act of approaching her/him may be the thing she/he has most dreaded: dealing with others knowing she/he is struggling.  So, approaching with sensitivity and caring is critical.  Pay attention to whether she/he is becoming overwhelmed by the discussion.  If she or he asks what it is you want to talk about, gently but confidently tell her or him what you know:  that you’re worried about someone you care about.</p>
                <p><i>“What is it?”</i></p>
                <p><i>"Well, I’m worried about you.  I’m worried about the way you are with food (or weight). I don’t know much about it, but what I do know is that you might be struggling with something that REALLY hurts inside and I want to help."</i></p>
                <p>There are a few things to pay attention to with the above suggestion of what to say.  Notice, first of all, that the term eating disorder is not part of what is said.  The eating behaviors or body image focus is not the actual problem.  These concerns are actually the consequences of the real problem. This leads to the 2nd thing to highlight about the above suggestion.  It emphasizes that the problem is something “that really hurts inside.”  A person struggling with disordered eating is hurting inside and most likely hurting a great deal.  Much of the hurt is that she/he experiences a great deal of shame about the problem and feels that  others will view her (or him) as “weak” or “disgusting” or “vain” or “superficial” and that nobody has any idea of the depth of the confusion and hurt.  Approaching a person struggling with disordered eating is most effective when it becomes what it should be: approaching somebody that is really hurting inside and has grown quite lonely in that hurt.</p>
            </div>
            <div>
                <h4>And Then What?</h4>
                <p>There can be no scripted guidelines on what to do from this point because the emotional experience that emerges will be unique to each collection of human beings involved.  Generally, you want to proceed if the person you are approaching indicates an open stance.  If she or he responds with anger or shutting down, perhaps even asking you to leave, then it’s important to respect her/him.  Simply re-iterate, quietly--not in an angry or defensive tone, that you meant to be helpful and apologize if you upset her/him.  Then, as you leave, offer her/him an open invitation to talk.</p>
                <p><i>“If you change you mind and feel like talking later, it’s okay.  Just let me know.”</i></p>
                <p>If she/he has not become closed off and guarded or very defensive and angry, it may mean that you have approached her/him with enough sensitivity and respect that she or he feels safe to move forward…. Perhaps, it is a tremendous relief to finally share this difficulty with somebody. She/He may become emotional…. In fact, you may, too. This is okay, and simply acknowledging tears with validating support-statements such as “I know this is really hard” or “I know this must really hurt inside” can be helpful. When you get to the point where you actually bring up the disordered eating behaviors, it’s important to focus on the behaviors as specifically as possible. Otherwise, you risk focusing on a “disorder” which feels more defining than specific behaviors. Also, since she/he will still likely have some level of defensiveness, it’s easy to debate whether or not one has an eating disorder, but harder to debate whether specific behaviors have occurred.</p>
                <p><i>"I notice you often don’t eat even when you’ve not eaten anything all day."</i></p>
                <p><i>"I see that you work out 3 times a day and it still doesn’t seem enough for you"</i></p>
                <p><i>"I find a large amount of food wrappers stuffed away."</i></p>
                <p>Keep in mind, however, that the most important thing to focus on is the emotional upheaval.  While it is helpful to refer to specific behaviors to be clear about what triggered your concern, your concern is really based on the emotional vulnerability the person you’re worried about is experiencing.  Therefore, it’s important to cite the emotional upheaval in an integrated fashion of describing your concern.</p>
                <p><i>"I see how much your  moods change and I know you must be really struggling inside"</i></p>
                <p><i>"I see all these warning signs I’ve learned about and I keep thinking how much you must be hurting."</i></p>
                <p>If you’ve gotten this far, then you’ve gotten far enough to suggest that she or he consider some professional help.  You may be surprise to learn that she or he is already seeing a therapist.  Encourage her/him to continue and by offering to be a part of the support team can be a tremendous gift.  Whether the person you’re worried about is currently seeing a mental health professional or will consider seeing one at your suggestion, having you offer anything that will reduce the aloneness that he or she likely feels can be more helpful than you may ever realize.</p>
                <p>If they are already seeing a mental health professional,</p>
                <p><i>“I’m glad you’ve got someone who understands a lot more about this than I do.  But if you ever just want to vent to a friend or talk about what has always seemed so important to keep inside, I’m willing to listen.  I want to listen.”</i></p>
                <p>If they are not already in counseling for this struggle,</p>
                <p><i>“I’d like you to think about seeing somebody, like a professional who knows more about this difficulty than I do.  But I also want to be there for you as much as I can.  If you ever want to talk about just anything that stresses you out or gets you mad or even somebody you really want to go out with…. anything…. I want you to know I can be a part of the support you need.  I can’t be the only support, because I don’t really know how to best help, but I do know you don’t have to go through it alone because I’m here for you if you ever just need to talk.”</i></p>
            </div>
            <div>
                <h4>Some Things To Consider</h4>
                <p>Here are some final things to consider as you plan to approach someone you care about and wish to help with their struggle with disordered eating.  As highlighted throughout this page, it’s important to avoid talking about food and weight as much as possible.  Never force them or pressure a person struggling with disordered eating to eat.  Not only does this add to the already tumultuous struggle they experience, it likely will force them away from ever considering you as someone who understands.  Also, as tempting as it may be to share your perceptions of how thin or how attractive the person struggling with disordered eating is, it’s important to not base your support on your perceptions of their thinness or attractiveness.  Although it may seem like a logical thing to compliment a person for being attractive, several negative consequences are possible.  The most likely thing is that they won’t believe that you’re telling the truth.  It isn’t so much that the person thinks you are a liar, but more that you are just saying something untrue out of kindness.  Or, they may believe that you are telling the truth from your perspective, but that it’s an incorrect perception.  Finally, often a person hears a compliment such as “You’re so thin already!” or “I think you are the most attractive person I’ve ever met” and interpret this as an indication that the disordered eating behavior is successfully giving them what they so desperately strive for.  One of the central factors that helps to maintain disordered eating is that the person struggling reduces him or herself to extremely concrete dimensions.  To pay compliments about physical features, however well intentioned, can serve to reinforce the distorted self-perception that physical features are what defines the individual.  Compliments about intelligence, kindness, humor, unique ideas, and assertiveness are likely to remind the person struggling that there is so much more to her than the number they are measuring themselves by.</p>
            </div>
            <div>
                <h4>Plant Seeds, Not Trees</h4>
                <p>Helping individuals struggling with disordered eating can be an emotionally draining experience if you begin to measure yourself by the same tangible results that they likely measures themselves by.  Keep in mind, your role is not to heal her/him or to remove the difficulties she/he is facing.  Your job is to do what you are able to reduce the aloneness she or he experiences in her or his struggle.  You may want to see quick results.   You may even reach a point where you feel you need to see the person make some visible changes for the better.  This is a recipe for frustration and possibly conflict.  It may take a long time because it’s far more than just eating behaviors and attitudes that need to change for growth and healing to take place.  It’s about learning to think about things in life differently.  It’s about learning to develop trust, perhaps for the first time in her or his life.   Think of yourself as a planter of seeds.  When you plant seeds, it takes quite a while for things to show up above ground that testify that a seed was ever planted.  Your friend or loved one that is struggling with disordered eating is a magnificent living being with many dimensions and components; it will take time for the roots to be restored, for them to learn how to use the nourishment to develop into a trunk, then begin expanding into branches, then giving birth to leaves and blossoming flowers or fruits.  You are not planting fully formed trees.  You’re offer of help and support is planting a seed of recovery and re-discovery for the person who has been struggling with disordered eating.</p>
            </div>
            <div>
                <h4>If You Need More Support</h4>
                <p>As you can imagine by this point, there is quite a lot involved in helping support a person struggling with disordered eating.  It can feel overwhelming and discouraging at times.  Help is available to help you deal with the confused feelings you may experience as you strive to be there for the person you’re worried about.  The staff at CAPS can consult with you on how to best approach or to listen as you need to talk about the challenges you’re facing. If you’d like some support or consultation in this endeavor, simply call 660-1000 and tell the receptionist you’d like to consult about someone you care about. You, like the person you care about, don’t have to go it alone.</p>
                <br>
                <p><i>© 2001. LifeShops. Gary D. Glass, Ph.D.</i></p>
            </div>
        </div>
    </b-col>
</b-row>
</template>

<script>
export default {
    name: 'ArticleDisorderedEating',
    components: {

    },
    data() {
        return {
            section: 0,
            titles: [
            'Disordered Eating',
            'Disordered Eating - Terms And Diagnosis',
            'Binge Eating',
            'Purging',
            'Diagnosis',
            'Anorexia (or Anorexia Nervosa)',
            'Bulimia Nervosa',
            'Disordered Eating Which Does Not Meet Diagnostic Criteria',
            'Understanding Disordered Eating',
            'A Different Kind of Hunger',
            'Emotional Upheaval and Powerful Feelings',
            'Feeling Hurt and Scared when Trying to Relate to Others',
            'Feeling Like a Failure When it Seems You Have to be Perfect',
            'It Is All About Control',
            'So It Also IS About Food?',
            'What Are You Really Hungry For?',
            'Trying to Make Life More Simple',
            'Disordered Eating: How To Help?',
            'Let Them Know They’re Not Alone',
            'Encourage Them to Seek Help',
            'Be Yourself',
            'Disordered Eating: What To Say?',
            'What To Say To Someone You’re Concerned About',
            'When and Where To Approach?',
            'Finding the Right Words',
            'Can We Talk?',
            'And Then What?',
            'Some Things To Consider',
            'Plant Seeds, Not Trees',
            'If You Need More Support',
            ]
        }
    }
}
</script>

<style scoped>

</style>
